apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ./../../base
images:
- name: PROJECT/BROADCASTER_APP_IMAGE
  newName: dilansachi/devopswk8s-ex410-broadcaster-app
  newTag: main-88522121d506122affa4e36dd2e80dfef2aebd3c
- name: PROJECT/TODO_APP_IMAGE
  newName: dilansachi/devopswk8s-ex410-todo-app
  newTag: main-88522121d506122affa4e36dd2e80dfef2aebd3c
- name: PROJECT/TODO_BACKEND_IMAGE
  newName: dilansachi/devopswk8s-ex410-todo-backend
  newTag: main-88522121d506122affa4e36dd2e80dfef2aebd3c
namespace: project-staging
