apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ./../../base
images:
- name: PROJECT/BROADCASTER_APP_IMAGE
  newName: dilansachi/devopswk8s-ex410-broadcaster-app
  newTag: main-08b89537475bf0c1c640997460b2bc2e6fa1b33d
- name: PROJECT/TODO_APP_IMAGE
  newName: dilansachi/devopswk8s-ex410-todo-app
  newTag: main-08b89537475bf0c1c640997460b2bc2e6fa1b33d
- name: PROJECT/TODO_BACKEND_IMAGE
  newName: dilansachi/devopswk8s-ex410-todo-backend
  newTag: main-08b89537475bf0c1c640997460b2bc2e6fa1b33d
namespace: project-staging
